### ISSUE TITLE
Bug: Music slider does not save when changed

### ISSUE THREAD

**Issue by ThatFridgeFella** [Firelance-Studios/ASMbugreports#9]
### What kind of problem is it?

Bug

### Describe the bug

If you attempted to change the sound level of the music, and then leave the menu, the sound bar will return to its original level of 50%.

### Map Name

All maps.

### To Reproduce

1. Open menu
2. Open options
3. Open audio
4. Change the music slider
5. Close out of the audio menu
6. Click back into the audio menu
7. See that the music slider has returned to its default level,

**Comment by OrinjiNeko** [comment]
fixed! will be out in the next update patch
